First apparently working version

diff --git a/.scripts/init-node b/.scripts/init-node
--- a/.scripts/init-node
+++ b/.scripts/init-node
@@ -5,6 +5,30 @@ SCRIPT="$(basename "${SCRIPT}")"
 
 set -euo pipefail
 
+timestamp()
+{
+	date -Ins -u
+}
+
+say()
+{
+	echo -e "$(timestamp): ${@}"
+}
+
+fail()
+{
+	say "❌ ${@}" 1>&2
+	exit ${EXIT_CODE:-1}
+}
+
+echo_run() {
+	local ARGS=("${@}")
+	say "${ARGS[@]@Q}"
+	"${@}"
+}
+
+[ -v K8S_ENGINE ] || fail "No K8S_ENGINE value is set"
+
 CRI_SOCKETS=(/var/run/cri-dockerd.sock /var/run/crio/crio.sock /var/run/containerd/containerd.sock)
 CRI=()
 for SOCKET in "${CRI_SOCKETS[@]}" ; do
@@ -23,50 +47,47 @@ FLAGS=(
 	--service-cidr "${SERVICE_CIDR}"
 )
 
-[ -v CONTROL_PLANE_ENDPOINT ] || CONTROL_PLANE_ENDPOINT=""
+case "${K8S_ENGINE}" in
+	k3d )	k3d cluster create || fail "Failed to initialize the k3d cluster (rc=${?})"
+		echo_run mkdir -p "${HOME}/.kube" || true
+		k3d kubeconfig get -a > "${HOME}/.kube/config"
+		echo_run chown -v $(id -u):$(id -g) "${HOME}/.kube/config"
+		exit 0
+		;;
 
-# From what we've seen, this is harmless if used all the time. However,
-# the exposure of this variable means that we can easily enough initialize
-# control plane nodes designed to use a shared endpoint IP (remember to
-# set up the HAP facade first!).
-[ -n "${CONTROL_PLANE_ENDPOINT}" ] || CONTROL_PLANE_ENDPOINT="127.0.0.1"
+	k8s )	echo_run systemctl start kubelet
 
-FLAGS+=(--control-plane-endpoint "${CONTROL_PLANE_ENDPOINT}")
+		# Next, init the cluster
+		echo_run kubeadm init --upload-certs "${CRI[@]}" "${FLAGS[@]}"
 
-echo_run() {
-	local ARGS=("${@}")
-	echo "${ARGS[@]@Q}"
-	"${@}"
-}
+		CA_UPDATER=()
+		CA_UPDATER+=(update-ca-trust:/etc/pki/ca-trust/source/anchors)
+		CA_UPDATER+=(update-ca-certificates:/usr/local/share/ca-certificates/)
+		for updater in "${CA_UPDATER[@]}" ; do
+			IFS=":" read ca target <<< "${updater}"
+			if type -P "${ca}" &>/dev/null ; then
+				echo_run cp -vf /etc/kubernetes/pki/ca.crt "${target}"/k8s-ca.crt
+				RC=0
+				echo_run "${ca}" || RC=${?}
+				[ ${RC} -eq 0 ] || say "⚠️ WARNING: ${ca} returned ${RC} ... certificate trusts may be incomplete!"
+				break
+			fi
+		done
 
-echo_run systemctl start kubelet
+		echo_run mkdir -p "${HOME}/.kube" || true
+		echo_run cp -vi /etc/kubernetes/admin.conf "${HOME}/.kube/config"
+		echo_run chown -v $(id -u):$(id -g) "${HOME}/.kube/config"
 
-# Next, init the cluster
-echo_run kubeadm init --upload-certs "${CRI[@]}" "${FLAGS[@]}"
+		# This will need to be run after each added node
+		echo_run kubectl taint nodes --all node-role.kubernetes.io/master- || true
+		# ONLY FOR SINGLE-NODE CLUSTERS
+		echo_run kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true
+		;;
 
-CA_UPDATER=()
-CA_UPDATER+=(update-ca-trust:/etc/pki/ca-trust/source/anchors)
-CA_UPDATER+=(update-ca-certificates:/usr/local/share/ca-certificates/)
-for updater in "${CA_UPDATER[@]}" ; do
-	IFS=":" read ca target <<< "${updater}"
-	if type -P "${ca}" &>/dev/null ; then
-		echo_run cp -vf /etc/kubernetes/pki/ca.crt "${target}"/k8s-ca.crt
-		RC=0
-		echo_run "${ca}" || RC=${?}
-		[ ${RC} -eq 0 ] || echo "WARNING: ${ca} returned ${RC} ... certificate trusts may be incomplete!"
-		break
-	fi
-done
-
-echo_run mkdir -p "${HOME}/.kube" || true
-echo_run cp -vi /etc/kubernetes/admin.conf "${HOME}/.kube/config"
-echo_run chown -v $(id -u):$(id -g) "${HOME}/.kube/config"
-
-# This will need to be run after each added node
-echo_run kubectl taint nodes --all node-role.kubernetes.io/master- || true
-# ONLY FOR SINGLE-NODE CLUSTERS
-echo_run kubectl taint nodes --all node-role.kubernetes.io/control-plane- || true
+	* )	fail "Unsupported K8s engine [${K8S_ENGINE}]" ;;
+esac
 
 # Some short display stuff
-echo_run kubectl get nodes
-echo_run kubectl get pods --all-namespaces
+echo_run kubectl get nodes || fail "Unable to enumerate the cluster's nodes... can't continue!"
+echo_run kubectl get pods --all-namespaces || fail "Unable to enumerate the cluster's pods... can't continue!"
+exit 0
diff --git a/initialize b/initialize
--- a/initialize
+++ b/initialize
@@ -5,20 +5,30 @@ SOURCE="${BASH_SOURCE:-${0}}"
 
 set -euo pipefail
 
+timestamp()
+{
+	date -Ins -u
+}
+
+say()
+{
+	echo -e "$(timestamp): ${@}"
+}
+
+fail()
+{
+	say "❌ ${@}" 1>&2
+	exit ${EXIT_CODE:-1}
+}
+
 DEF_BOOT_TIMEOUT=90
 MIN_BOOT_TIMEOUT=15
 
 SCRIPTS="${BASEDIR}/.scripts"
 [ -v K8S_CONF ] || K8S_CONF="${BASEDIR}/conf"
 
-say() {
-	echo -e "${@}"
-}
-
-fail() {
-	say "${@}" 1>&2
-	exit ${EXIT_CODE:-1}
-}
+[ -v K8S_ENGINE ] || fail "No K8s engine value is set"
+[ -v K8S_ENGINE ] || fail "No K8S_ENGINE value is set"
 
 get_pod_ready_status() {
 	local PODS=""
@@ -74,9 +84,7 @@ OUT="$("${BASEDIR}/clear-node" 2>&1)" || RC=${?}
 # Initialize Kubernetes
 #
 say "Initializing the K8s node"
-OUT="$("${SCRIPTS}/init-node" 2>&1)" || RC=${?}
-[ ${RC} -eq 0 ] || fail "Failed during node initialization:\n${OUT}"
-
+"${SCRIPTS}/init-node" || fail "Failed during node initialization (rc=${?})"
 
 [ -v BOOT_TIMEOUT ] || BOOT_TIMEOUT=${DEF_BOOT_TIMEOUT}
 [[ "${BOOT_TIMEOUT}" =~ ^[1-9][0-9]*$ ]] || BOOT_TIMEOUT=${DEF_BOOT_TIMEOUT}
@@ -103,12 +111,30 @@ while true ; do
 done
 say ""
 
-#
-# Add Calico
-#
-say "Installing Calico"
-OUT="$("${SCRIPTS}/init-calico" 2>&1)" || RC=${?}
-[ ${RC} -eq 0 ] || fail "Failed to install Calico: \n${OUT}"
+# Identify the type of cluster - K3d or K8s
+
+
+case "${K8S_ENGINE}" in
+	k8s )	#
+		# Add Calico
+		#
+		say "Installing Calico"
+		OUT="$("${SCRIPTS}/init-calico" 2>&1)" || RC=${?}
+		[ ${RC} -eq 0 ] || fail "Failed to install Calico: \n${OUT}"
+
+		#
+		# Add K8s metrics
+		#
+		say "Deploying the K8s metrics"
+		OUT="$("${SCRIPTS}/init-metrics" 2>&1)" || RC=${?}
+		[ ${RC} -eq 0 ] || fail "Failed to install the K8s metrics: \n${OUT}"
+		;;
+	k3d )	#
+		;;
+
+	* )	fail "Unknown k8s engine [${K8S_ENGINE}]"
+		;;
+esac
 
 #
 # Add HAProxy
@@ -123,13 +149,6 @@ OUT="$("${SCRIPTS}/init-hap" "${K8S_CONF}/haproxy-ingress-values.yaml" 2>&1)" ||
 say "Deploying the K8s dashboard"
 OUT="$(kubectl apply -f "${K8S_CONF}/k8s-dashboard.yaml" 2>&1)" || RC=${?}
 [ ${RC} -eq 0 ] || fail "Failed to install the K8s dashboard: \n${OUT}"
-
-#
-# Add K8s metrics
-#
-say "Deploying the K8s metrics"
-OUT="$("${SCRIPTS}/init-metrics" 2>&1)" || RC=${?}
-[ ${RC} -eq 0 ] || fail "Failed to install the K8s metrics: \n${OUT}"
 
 #
 # Create the AWS pull secret on the main namespace, as a template
diff --git a/ubuntu-k8s-init b/ubuntu-k8s-init
--- a/ubuntu-k8s-init
+++ b/ubuntu-k8s-init
@@ -3,14 +3,32 @@ SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
 BASEDIR="$(dirname "${SCRIPT}")"
 SCRIPT="$(basename "${SCRIPT}")"
 
+set -euo pipefail
+
+timestamp()
+{
+	date -Ins -u
+}
+
+say()
+{
+	echo -e "$(timestamp): ${@}"
+}
+
+fail()
+{
+	say "❌ ${@}" 1>&2
+	exit ${EXIT_CODE:-1}
+}
+
 SCRIPTS="${BASEDIR}/.scripts"
+
+DEFAULT_K8S_ENGINE="k3d"
 
 list_kernels()
 {
 	dpkg -l | egrep "linux-image-[56]" | awk '{ print $2 }' | sort -u
 }
-
-set -euo pipefail
 
 if [ "$(/usr/bin/id -u)" != "0" ] ; then
 
@@ -26,9 +44,10 @@ if [ "$(/usr/bin/id -u)" != "0" ] ; then
 	#
 	# Do the rooty-things
 	#
-	echo "👉 Not running as root, must escalate privileges!"
-	sudo -EH "${0}" "${@}" || { echo "	❌ Root installation tasks failed (rc=${?})!" ; exit 1 ; }
-	echo "	✅ Root portions completed!"
+	say "👉 Not running as root, must escalate privileges!"
+	sudo -EH "${0}" "${@}" || fail "\tRoot installation tasks failed (rc=${?})!"
+	say "\t✅ Root portions completed!"
+	exit 0
 
 	#
 	# Take stock of the new kernel versions installed
@@ -42,9 +61,14 @@ if [ "$(/usr/bin/id -u)" != "0" ] ; then
 	#
 	# Set up the K8s configuration
 	#
-	echo "👉 Configuring your K8s cluster settings"
 	mkdir -p ~/.kube
-	sudo cat /etc/kubernetes/admin.conf > ~/.kube/config
+	say "👉 Configuring your K8s cluster settings"
+	ADMIN_CONF="/etc/kubernetes/admin.conf"
+	if [ -f "${ADMIN_CONF}" ] ; then
+		sudo cat "${ADMIN_CONF}"
+	else
+		k3d kubeconfig get -a
+	fi > ~/.kube/config
 	chown -R "${USER}:" ~/.kube
 	chmod -R go-rwx ~/.kube
 
@@ -53,34 +77,32 @@ if [ "$(/usr/bin/id -u)" != "0" ] ; then
 	#
 	"${SCRIPTS}/init-aws-config"
 
-	echo ""
-	echo ""
-	echo ""
-	echo "	✅ Installation completed. You should now be able to operate"
-	echo "	  Docker and Kubernetes locally"
-	echo ""
+	say ""
+	say "\t✅ Installation completed. You should now be able to operate"
+	say "\t   Docker and Kubernetes locally"
+	say ""
 
 	if docker ps -a &>/dev/null ; then
-		echo "	✅ Docker control is enabled"
+		say "\t✅ Docker control is enabled"
 	else
-		echo "	❌ Your group memberships haven't been updated, you must"
-		echo "	  log out and back in to enable control of Docker"
+		say "\t❌ Your group memberships haven't been updated, you must"
+		say "\t   log out and back in to enable control of Docker"
 	fi
-	echo ""
+	say ""
 
 	if kubectl get pods -A &>/dev/null ; then
-		echo "	✅ Kubernetes control is enabled"
+		say "\t✅ Kubernetes control is enabled"
 	else
-		echo "	❌ Your Kubernetes configuration seems to be incorrect,"
-		echo "	  please fix it before continuing. Feel free to ask for"
-		echo "	  help if you feel it's necessary."
+		say "\t❌ Your Kubernetes configuration seems to be incorrect,"
+		say "\t   please fix it before continuing. Feel free to ask for"
+		say "\t   help if you feel it's necessary."
 	fi
-	echo ""
+	say ""
 
 	if [ "${OLD_KERNELS}" != "${NEW_KERNELS}" ] ; then
-		echo "	👉 New kernels were installed, it's strongly recommended that you"
-		echo "	  reboot to ensure the latest software is running."
-		echo ""
+		say "\t👉 New kernels were installed, it's strongly recommended that you"
+		say "\t   reboot to ensure the latest software is running."
+		say ""
 	fi
 
 	exit 0
@@ -95,12 +117,12 @@ is_installed() {
 TRUSTED_GPG_DIR="/etc/apt/trusted.gpg.d"
 APT_SOURCES_DIR="/etc/apt/sources.list.d"
 
-[ -v SUDO_USER ] && echo "✅ Privileges escalated! Proceeding with the installation"
+[ -v SUDO_USER ] && say "✅ Privileges escalated! Proceeding with the installation"
 
 #
 # Full updates
 #
-echo "👉 Performing a full package update..."
+say "👉 Performing a full package update..."
 apt-get update && apt-get -f -y dist-upgrade && apt-get clean
 
 #
@@ -126,9 +148,9 @@ for P in "${EXTRA_PACKAGES[@]}" ; do
 	is_installed "${P}" || MISSING_PACKAGES+=("${P}")
 done
 if [ ${#MISSING_PACKAGES[@]} -eq 0 ] ; then
-	echo "✅ All required packages are installed"
+	say "✅ All required packages are installed"
 else
-	echo "👉 Installing extra packages: [${MISSING_PACKAGES[@]}]..."
+	say "👉 Installing extra packages: [${MISSING_PACKAGES[@]}]..."
 	apt-get install -y "${MISSING_PACKAGES[@]}"
 fi
 
@@ -136,9 +158,9 @@ fi
 # Disable swap
 #
 if [ -z "$(swapon --show --noheadings --raw)" ] ; then
-	echo "✅ Swap is disabled as required by Kubernetes"
+	say "✅ Swap is disabled as required by Kubernetes"
 else
-	echo "👉 Disabling swap (required by Kubernetes)"
+	say "👉 Disabling swap (required by Kubernetes)"
 	swapoff -a
 	grep -v "[[:space:]]swap[[:space:]]" /etc/fstab | sponge /etc/fstab
 fi
@@ -147,15 +169,15 @@ fi
 # Install and configure Docker
 #
 if docker ps -a &>/dev/null ; then
-	echo "✅ Docker is already installed and running"
+	say "✅ Docker is already installed and running"
 else
 
 	if is_installed docker ; then
-		echo "✅ Docker is already installed"
+		say "✅ Docker is already installed"
 	else
 		[ -v DOCKER_DISTRO ] || DOCKER_DISTRO=""
 		[ -n "${DOCKER_DISTRO}" ] || DOCKER_DISTRO="jammy"
-		echo "👉 Installing Docker..."
+		say "👉 Installing Docker..."
 		rm -f "${TRUSTED_GPG_DIR}/docker.gpg" &>/dev/null || true
 		curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor -o "${TRUSTED_GPG_DIR}/docker.gpg"
 		chmod a+r "${TRUSTED_GPG_DIR}/docker.gpg"
@@ -176,27 +198,27 @@ else
 		[ -v SUDO_USER ] && usermod -a -G docker "${SUDO_USER}"
 	fi
 
-	echo "👉 Enabling the Docker service..."
+	say "👉 Enabling the Docker service..."
 	systemctl enable --now docker.service docker.socket
 	docker run hello-world
 fi
 
 if systemctl is-active --quiet cri-docker.service  ; then
-	echo "✅ CRI-Docker is already installed and running"
+	say "✅ CRI-Docker is already installed and running"
 else
 	if is_installed cri-dockerd ; then
-		echo "✅ CRI-Docker is already installed"
+		say "✅ CRI-Docker is already installed"
 	else
 		[ -v CRI_VER ] || CRI_VER=""
 		[ -n "${CRI_VER}" ] || CRI_VER="0.3.4"
 		[ -v CRI_DISTRO ] || CRI_DISTRO=""
 		[ -n "${CRI_DISTRO}" ] || CRI_DISTRO="jammy"
-		echo "👉 Installing CRI-Docker v${CRI_VER} (${CRI_DISTRO})..."
+		say "👉 Installing CRI-Docker v${CRI_VER} (${CRI_DISTRO})..."
 		wget "https://github.com/Mirantis/cri-dockerd/releases/download/v${CRI_VER}/cri-dockerd_${CRI_VER}.3-0.ubuntu-${CRI_DISTRO}_amd64.deb"
 		apt-get install -y "./cri-dockerd_${CRI_VER}.3-0.ubuntu-${CRI_DISTRO}_amd64.deb"
 		rm -rf "./cri-dockerd_${CRI_VER}.3-0.ubuntu-${CRI_DISTRO}_amd64.deb" || true
 	fi
-	echo "👉 Enabling CRI-Docker..."
+	say "👉 Enabling CRI-Docker..."
 	systemctl enable --now cri-docker.service cri-docker.socket
 	# This will verify that it's running
 	systemctl is-active --quiet cri-docker.service
@@ -206,11 +228,11 @@ fi
 # Install Helm
 #
 if helm version &>/dev/null ; then
-	echo "✅ Helm is already installed"
+	say "✅ Helm is already installed"
 else
 	[ -v HELM_VER ] || HELM_VER=""
 	[ -n "${HELM_VER}" ] || HELM_VER="3.12.3"
-	echo "👉 Installing Helm v${HELM_VER}..."
+	say "👉 Installing Helm v${HELM_VER}..."
 	curl -fsSL https://get.helm.sh/helm-v${HELM_VER}-linux-amd64.tar.gz | tar -C /usr/local/bin --strip-components=1 -xzvf - linux-amd64/helm
 	helm version &>/dev/null
 fi
@@ -218,44 +240,67 @@ fi
 #
 # Install Kubernetes
 #
-if kubeadm version &>/dev/null ; then
-	echo "✅ Kubernetes already installed"
+if kubectl version &>/dev/null ; then
+	say "✅ Kubernetes already installed"
 else
 	[ -v K8S_VER ] || K8S_VER=""
 	[ -n "${K8S_VER}" ] || K8S_VER="1.28"
-	echo "👉 Installing Kubernetes v${K8S_VER}..."
+	say "👉 Installing Kubernetes v${K8S_VER}..."
 	rm -f "${TRUSTED_GPG_DIR}/kubernetes.gpg" &>/dev/null || true
 	curl -fsSL "https://pkgs.k8s.io/core:/stable:/v${K8S_VER}/deb/Release.key" | gpg --dearmor -o "${TRUSTED_GPG_DIR}/kubernetes.gpg"
 	echo "deb https://pkgs.k8s.io/core:/stable:/v${K8S_VER}/deb/ /" > "${APT_SOURCES_DIR}/kubernetes.list"
 	apt-get update
-	apt-get install -y kubelet kubeadm kubectl
+	apt-get install -y kubectl
+
+	[ -v K8S_ENGINE ] || K8S_ENGINE=""
+	[ -n "${K8S_ENGINE}" ] || K8S_ENGINE="${DEFAULT_K8S_ENGINE}"
+	export K8S_ENGINE="${K8S_ENGINE,,}"
+	case "${K8S_ENGINE}" in
+		k3d )	[ -v K3D_URL ] || K3D_URL=""
+			[ -n "${K3D_URL}" ] || K3D_URL="https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh"
+
+			[ -v K3D_TAG ] || K3D_TAG=""
+			[ -n "${K3D_TAG}" ] && export TAG="${K3D_TAG}"
+			say "👉 Installing K3d (${TAG:-latest}) from [${K3D_URL}] ..."
+			curl -fsSL "${K3D_URL}" | bash
+			unset TAG
+			;;
+
+		k8s )	say "👉 Installing Kubelet & Kubeadm v${K8S_VER}..."
+			apt-get install -y kubelet kubeadm
+			;;
+
+		* )	fail "❌ unknown K8s engine [${K8S_ENGINE}]" ;;
+	esac
+
+	(
+		say "👉 Initializing the Kubernetes ${K8S_ENGINE} cluster node..."
+		set -euo pipefail
+		cd "${BASEDIR}"
+		( cd tools && tar -czf - . ) | tar -C /usr/local/bin -xzvf -
+		[ -v CLUSTER_CIDR ] && say "\t👉 CLUSTER_CIDR=[${CLUSTER_CIDR}]"
+		[ -v SERVICE_CIDR ] && say "\t👉 SERVICE_CIDR=[${SERVICE_CIDR}]"
+		exec ./initialize
+	) || fail "❌ failed to initialize the ${K8S_ENGINE} cluster (rc=${?})"
 fi
 
 #
 # Initialize the K8s node
 #
 if kubectl get pods -A &>/dev/null ; then
-	echo "✅ The Kubernetes node is already initialized"
+	say "✅ The Kubernetes node is already initialized"
 else
-	(
-		echo "👉 Initializing the Kubernetes cluster node..."
-		set -euo pipefail
-		cd "${BASEDIR}"
-		( cd tools && tar -czf - . ) | tar -C /usr/local/bin -xzvf -
-		[ -v CLUSTER_CIDR ] && echo "	👉 CLUSTER_CIDR=[${CLUSTER_CIDR}]"
-		[ -v SERVICE_CIDR ] && echo "	👉 SERVICE_CIDR=[${SERVICE_CIDR}]"
-		./initialize
-	)
+	fail "The Kubernetes node doesn't appear to be propely initialized"
 fi
 
 #
 # Install AWS CLI
 #
 if aws --version &>/dev/null ; then
-	echo "✅ AWS CLI already installed"
+	say "✅ AWS CLI already installed"
 else
 	(
-		echo "👉 Installing AWS CLI..."
+		say "👉 Installing AWS CLI..."
 		set -euo pipefail
 		cd
 		curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
