Modify init-kubeconfig to surgically add the new stuff
This avoids undesired consolidations and allows the preservation of configuration patterns (i.e. file-based stuff)

diff --git a/.scripts/init-kubeconfig b/.scripts/init-kubeconfig
--- a/.scripts/init-kubeconfig
+++ b/.scripts/init-kubeconfig
@@ -33,7 +33,18 @@ fail()
 
 cleanup()
 {
-	rm -rf "${NEW_CONFIG}" &>/dev/null || true
+	[ -n "${NEW_CONFIG:-}" ] && shred -u "${NEW_CONFIG}" &>/dev/null || true
+	if [ -n "${CONFIG_ERROR:-}" ] ; then
+		[ -n "${CTX_CA_CRT_FILE:-}" ] && shred -u "${CTX_CA_CRT_FILE}" &>/dev/null || true
+		[ -n "${CTX_USER_CRT_FILE:-}" ] && shred -u "${CTX_USER_CRT_FILE}" &>/dev/null || true
+		[ -n "${CTX_USER_KEY_FILE:-}" ] && shred -u "${CTX_USER_KEY_FILE}" &>/dev/null || true
+	fi
+	if [ -n "${TOKEN_ERROR:-}" ] ; then
+		[ -n "${CTX_TOKEN_FILE:-}" ] && shred -u "${CTX_TOKEN_FILE}" &>/dev/null || true
+	else
+		[ -n "${CTX_USER_CRT_FILE:-}" ] && shred -u "${CTX_USER_CRT_FILE}" &>/dev/null || true
+		[ -n "${CTX_USER_KEY_FILE:-}" ] && shred -u "${CTX_USER_KEY_FILE}" &>/dev/null || true
+	fi
 }
 
 CURRENT_USER="$(id -un)"
@@ -44,35 +55,103 @@ if [ ! -d "${HOME}" ] ; then
 	exit 0
 fi
 
-KUBE_DIR="${HOME}/.kube"
-MASTER="${KUBE_DIR}/config"
-NEW_CONFIG="/etc/kubernetes/admin.conf"
-
-say "👉 Configuring your K8s cluster access settings"
+export NEW_CONFIG="/etc/kubernetes/admin.conf"
 TGT="$(mktemp)"
 sudo cat "${NEW_CONFIG}" > "${TGT}"
-NEW_CONFIG="${TGT}"
+export NEW_CONFIG="${TGT}"
 trap cleanup EXIT
 unset TGT
 
-# Change the names for convenience
-sed -i \
-	-e 's;\(user\|name\):\s\+kubernetes-admin$;\1: local;g' \
-	-e 's;\(cluster\|name\):\s\+kubernetes$;\1: local;g' \
-	-e 's;\(current-context\|name\):\s\+kubernetes-admin@kubernetes$;\1: local;g' \
-	"${NEW_CONFIG}"
+KUBE_DIR="${HOME}/.kube"
+OUT="$(mkdir -p "${KUBE_DIR}" 2>&1)" || fail "Couldn't create the directory [${KUBE_DIR}] (rc=${?}): ${OUT}"
 
-export KUBECONFIG="${NEW_CONFIG}:${MASTER}"
-mkdir -p "${KUBE_DIR}"
+get_config_value()
+{
+	local JSONPATH="${1}"
+	kubectl --kubeconfig="${NEW_CONFIG}" config view --raw --output jsonpath="{ ${JSONPATH} }"
+}
 
-say "👉 Merging the kubeconfig data into the master file"
-kubectl config view --flatten | sponge "${MASTER}"
+say "👉 Configuring your K8s cluster access settings"
+
+export CONFIG_ERROR="true"
+export KUBECONFIG="${KUBE_DIR}/config"
+
+# Get all the configurations!
+CTX_NAME="local"
+
+CTX_CLUSTER="${CTX_NAME}"
+CTX_PREFIX=".clusters[0].cluster"
+CTX_CA_CRT="$(get_config_value "${CTX_PREFIX}.certificate-authority-data" 2>&1)" || fail "Failed to read the CA certificate data from the new configuration (rc=${?}): ${CTX_CA_CRT}"
+CTX_URL="$(get_config_value "${CTX_PREFIX}.server" 2>&1)" || fail "Failed to read the server URL from the new configuration (rc=${?}): ${CTX_URL}"
+
+CTX_USER="${CTX_NAME}"
+CTX_PREFIX=".users[0].user"
+CTX_USER_CRT="$(get_config_value "${CTX_PREFIX}.client-certificate-data" 2>&1)" || fail "Failed to read the admin user's certificate from the new configuration (rc=${?}): ${CTX_USER_CRT}"
+CTX_USER_KEY="$(get_config_value "${CTX_PREFIX}.client-key-data" 2>&1)" || fail "Failed to read the admin user's private key from the new configuration (rc=${?}): ${CTX_USER_KEY}"
+
+# Got everything! Now set it up!
+CTX_CA_CRT_FILE="${KUBE_DIR}/${CTX_NAME}.crt"
+CTX_USER_CRT_FILE="${KUBE_DIR}/${CTX_NAME}-user.crt"
+CTX_USER_KEY_FILE="${KUBE_DIR}/${CTX_NAME}-user.key"
+
+OUT="$( ( base64 -d <<< "${CTX_CA_CRT}" > "${CTX_CA_CRT_FILE}" ) 2>&1 )" || fail "Failed to create the file for the CA certificate data (rc=${?}): ${OUT}"
+OUT="$(openssl x509 -noout -in "${CTX_CA_CRT_FILE}" 2>&1)" || fail "Invalid certificate file for the CA certificate (rc=${?}): ${OUT}"
+
+OUT="$( ( base64 -d <<< "${CTX_USER_CRT}" > "${CTX_USER_CRT_FILE}" ) 2>&1 )" || fail "Failed to create the file for the user's certificate (rc=${?}): ${OUT}"
+OUT="$(openssl x509 -noout -in "${CTX_USER_CRT_FILE}" 2>&1)" || fail "Invalid certificate file for the user's certificate (rc=${?}): ${OUT}"
+OUT="$( ( base64 -d <<< "${CTX_USER_KEY}" > "${CTX_USER_KEY_FILE}" ) 2>&1 )" || fail "Failed to create the file for the user's private key (rc=${?}): ${OUT}"
+OUT="$(openssl rsa -check -noout -in "${CTX_USER_KEY_FILE}" 2>&1)" || fail "Invalid key file for the user's private key (rc=${?}): ${OUT}"
+
+# Make sure the key and cert match, and they match the CA
+A="$(openssl rsa -noout -modulus -in "${CTX_USER_KEY_FILE}" 2>&1)" || fail "Failed to compute the modulus for the user's private key (rc=${?}): ${A}"
+B="$(openssl x509 -noout -modulus -in "${CTX_USER_CRT_FILE}" 2>&1)" || fail "Failed to compute the modulus for the user's certificate (rc=${?}): ${B}"
+[ "${A}" == "${B}" ] || fail "Modulus mismatch between the user's certificate and private key: rsa=[${A}] crt=[${B}]"
+
+OUT="$(openssl verify -no-CAstore -no-CApath -CAfile "${CTX_CA_CRT_FILE}" "${CTX_USER_CRT_FILE}" 2>&1)" || fail "Failed to verify the relationship between the CA and the user's certificate (rc=${?}): ${OUT}"
+
+# We're good to go! Add the items!
+OUT="$(kubectl config set-cluster "${CTX_CLUSTER}" --certificate-authority="${CTX_CA_CRT_FILE}" --server="${CTX_URL}" --embed-certs=false 2>&1)" || fail "Failed to add the cluster named [${CTX_CLUSTER}] (rc=${?}): ${OUT}"
+OUT="$(kubectl config set-credentials "${CTX_USER}" --client-certificate="${CTX_USER_CRT_FILE}" --client-key="${CTX_USER_KEY_FILE}" --embed-certs=false 2>&1)" || fail "Failed to add the user named [${CTX_USER}] (rc=${?}): ${OUT}"
+OUT="$(kubectl config set-context "${CTX_NAME}" --cluster="${CTX_CLUSTER}" --user="${CTX_USER}" 2>&1)" || fail "Failed to add the context named [${CTX_NAME}] (rc=${?}): ${OUT}"
 
 # Make sure we're using the local context
-kubectl config use-context local || fail "Failed to set the current context to 'local'"
+OUT="$(kubectl config use-context "${CTX_NAME}" 2>&1)" || fail "Failed to set the current context to '${CTX_NAME}' (rc=${?}): ${OUT}"
 
-chown -R "${CURRENT_USER}:" "${KUBE_DIR}"
-chmod -R go-rwx "${KUBE_DIR}"
+# Avoid deletion of files
+export CONFIG_ERROR=""
+
+export TOKEN_ERROR="true"
+
+# Now we do the token thing!
+ADMIN_NAMESPACE="kube-system"
+ADMIN_USER="admin"
+if ! kubectl --context "${CTX_NAME}" --namespace "${ADMIN_NAMESPACE}" get serviceaccount "${ADMIN_USER}" &>/dev/null ; then
+	OUT="$(kubectl --context "${CTX_NAME}" --namespace "${ADMIN_NAMESPACE}" create serviceaccount "${ADMIN_USER}" 2>&1)" || fail "Failed to create the ${ADMIN_USER} service account (rc=${?}): ${OUT}"
+fi
+ok "Admin service account ready!"
+
+ADMIN_ROLE="cluster-admin"
+if ! kubectl --context "${CTX_NAME}" get clusterrolebinding "${ADMIN_ROLE}:${ADMIN_USER}" &>/dev/null ; then
+	OUT="$(kubectl --context "${CTX_NAME}" create clusterrolebinding "${ADMIN_ROLE}:${ADMIN_USER}" --clusterrole="${ADMIN_ROLE}" --serviceaccount="${ADMIN_NAMESPACE}:${ADMIN_USER}" 2>&1)" || fail "Failed to create the ClusterRoleBinding between ${ADMIN_ROLE} and ${ADMIN_USER}"
+fi
+ok "ClusterRoleBinding ready!"
+
+DURATION="87600h"
+TOKEN="$(kubectl --context "${CTX_NAME}" --namespace "${ADMIN_NAMESPACE}" create token "${ADMIN_USER}" --duration="${DURATION}" 2>&1)" || fail "Failed to create a bearer token for local cluster admin access (rc=${?}): ${TOKEN}"
+
+CTX_TOKEN_FILE="${KUBE_DIR}/${CTX_NAME}.tok"
+OUT="$( ( echo -n "${TOKEN}" > "${CTX_TOKEN_FILE}" ) 2>&1)" || fail "Failed to create the admin user's token file (rc=${?}): ${OUT}"
+ok "Token file created!"
+
+OUT="$(kubectl config set "users.${CTX_USER}.tokenFile" "$(readlink -f "${CTX_TOKEN_FILE}")" 2>&1)" || fail "Failed to set the token file for the admin user (rc=${?}): ${OUT}"
+ok "Token configured!"
+export TOKEN_ERROR=""
+
+OUT="$(kubectl config unset "users.${CTX_USER}.client-certificate" 2>&1)" || err "Failed to clear the admin user's certificate (rc=${?}): ${OUT}"
+OUT="$(kubectl config unset "users.${CTX_USER}.client-key" 2>&1)" || err "Failed to clear the admin user's private key (rc=${?}): ${OUT}"
+
+OUT="$(chown -Rv "${CURRENT_USER}:" "${KUBE_DIR}" 2>&1)" || fail "Failed to set the correct ownership for the config directory (rc=${?}): ${OUT}"
+OUT="$(chmod -Rv go-rwx "${KUBE_DIR}" 2>&1)" || fail "Failed to set the correct permissions for the config directory (rc=${?}): ${OUT}"
 
 kubectl config get-contexts
 ok "Cluster access configured"
