Fix container creation scripts, also use the base-container-scripts container

diff --git a/.scripts/install-act b/.scripts/install-act
--- a/.scripts/install-act
+++ b/.scripts/install-act
@@ -40,6 +40,7 @@ fail()
 
 cleanup()
 {
+	[ -n "${CID:-}" ] && rm -rf "${CID}" &>/dev/null
 	if [ -n "${CONTAINER:-}" ] ; then
 		doing "Removing the created container (${CONTAINER}) ..."
 		OUT="$(docker container rm --force --volumes "${CONTAINER}" 2>&1)" \
@@ -70,23 +71,30 @@ else
 	usage
 fi
 
+if [ "$(/usr/bin/id -u)" != "0" ] ; then
+	say "⚠️ Not running as root, must escalate privileges!"
+	exec sudo -EH "PATH=${PATH}" "${0}" "${@}"
+fi
+
 mkdir -p "${TGT_DIR}" &>/dev/null || true
 [ -e "${TGT_DIR}" ] || fail "The directory [${TGT_DIR}] does not exist and could not be created!"
 [ -d "${TGT_DIR}" ] || fail "The path [${TGT_DIR}] is not a directory"
 [ -w "${TGT_DIR}" ] || fail "The directory [${TGT_DIR}] is not writable"
 
-RC=0
-echo "Creating the container for [${IMAGE}]..."
-CONTAINER="$(docker create "${IMAGE}")" || fail "Failed to create the container (rc=${?}): ${CONTAINER}"
 trap cleanup EXIT
+
+echo "Creating the container for [${IMAGE}]..."
+CID="$(mktemp --tmpdir=/tmp .container-id.XXXXXX 2>&1)" || fail "Failed to create a temporary file (rc=${?}): ${CID}"
+rm -f "${CID}" &>/dev/null || true
+CONTAINER="$(docker create --pull always --cidfile "${CID}" --entrypoint /dev/null "${IMAGE}" 2>&1)" || fail "Failed to create the container (rc=${?}): ${CONTAINER}"
+CONTAINER="$(<"${CID}")" || fail "Failed to read the Container ID from [${CID}]"
 ok "Container ready with ID ${CONTAINER}!"
 
 TARGET="${TGT_DIR}/${TGT_ACT}"
 doing "Extracting the source executable [${SRC_ACT}] into [${TARGET}] ..."
 CMD=( docker cp "${CONTAINER}:/${SRC_ACT}" "${TARGET}" )
 
-OUT="$( "${CMD[@]}" 2>&1)" || RC=${?}
-[ ${RC} -eq 0 ] || fail "Failed to copy the executable as [${TARGET}] (rc=${RC}): ${OUT}"
+OUT="$( "${CMD[@]}" 2>&1)" || fail "Failed to copy the executable as [${TARGET}] (rc=${?}): ${OUT}"
 
 ok "Installation complete!"
 exec "${TARGET}" --version
diff --git a/.scripts/install-base-scripts b/.scripts/install-base-scripts
--- a/.scripts/install-base-scripts
+++ b/.scripts/install-base-scripts
@@ -40,6 +40,7 @@ fail()
 
 cleanup()
 {
+	[ -n "${CID:-}" ] && rm -rf "${CID}" &>/dev/null
 	if [ -n "${CONTAINER:-}" ] ; then
 		doing "Removing the created container (${CONTAINER}) ..."
 		OUT="$(docker container rm --force --volumes "${CONTAINER}" 2>&1)" \
@@ -48,32 +49,32 @@ cleanup()
 	fi
 }
 
+if [ "$(/usr/bin/id -u)" != "0" ] ; then
+	say "⚠️ Not running as root, must escalate privileges!"
+	exec sudo -EH "PATH=${PATH}" "${0}" "${@}"
+fi
+
 REG="public.ecr.aws"
-REPO="arkcase/base"
+REPO="arkcase/base-container-scripts"
 VER="latest"
 IMAGE="${REG}/${REPO}:${VER}"
 
-RC=0
-echo "Creating the container for [${IMAGE}]..."
-CONTAINER="$(docker create --pull always "${IMAGE}")" || fail "Failed to create the container (rc=${?})"
 trap cleanup EXIT
+
+echo "Creating the container for [${IMAGE}]..."
+CID="$(mktemp --tmpdir=/tmp .container-id.XXXXXX 2>&1)" || fail "Failed to create a temporary file (rc=${?}): ${CID}"
+rm -f "${CID}" &>/dev/null || true
+CONTAINER="$(docker create --pull always --cidfile "${CID}" --entrypoint /dev/null "${IMAGE}" 2>&1)" || fail "Failed to create the container (rc=${?}): ${CONTAINER}"
+CONTAINER="$(<"${CID}")" || fail "Failed to read the Container ID from [${CID}]"
 ok "Container ready with ID ${CONTAINER}!"
 
-SCRIPTS=(
-	/.functions
-	/usr/local/bin/decrypt
-	/usr/local/bin/encrypt
-	/usr/local/bin/find-ssl-dirs
-	/usr/local/bin/fips-enabled
-	/usr/local/bin/json2yaml
-	/usr/local/bin/mvn-crypt
-	/usr/local/bin/mvn-get
-	/usr/local/bin/xmlenvsubst
-	/usr/local/bin/yaml2json
+doing "Copying the common-use scripts ..."
+SRC_ITEMS=(
+	.functions
+	usr/local/bin/
 )
-
-doing "Copying the scripts..."
-for SCRIPT in "${SCRIPTS[@]}" ; do
-	docker cp "${CONTAINER}:${SCRIPT}" "${SCRIPT}" || fail "Failed to copy [${SCRIPT}] (rc=${?})"
+for SRC in "${SRC_ITEMS[@]}" ; do
+	doing "Installing [${SRC}] ..."
+	OUT="$( docker cp "${CONTAINER}:/${SRC}" "/${SRC}" )" || fail "Failed to copy [${SRC}] (rc=${?}): ${OUT}"
+	ok "Installed!"
 done
-ok "Scripts copied!"
diff --git a/tools/wait-log b/tools/wait-log
--- a/tools/wait-log
+++ b/tools/wait-log
@@ -7,6 +7,8 @@
 
 set -euo pipefail
 
+CALLED="${BASH_ARGV0:-${BASH_SOURCE:-${0}}}"
+
 timestamp()
 {
 	date -Ins -u
@@ -17,37 +19,123 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
 usage()
 {
-	echo -e "usage: ${BASH_SOURCE:-${0}} pod [container]" 1>&2
+	[ ${#} -eq 0 ] || err "${@}\n"
+	echo -e "usage: ${CALLED} [ -h | -? | --help ] [ -d | --debug ] [ --context context ] [ -n namespace | --namespace namespace ] [ -t timeout | --timeout timeout ] pod [ container ]" 1>&2
 	exit 1
 }
 
-[ ${#} -ge 1 ] || usage
-[ ${#} -le 2 ] || usage
+ARGS="$(getopt -o "h?dn:t:" -l "help,debug,context:,namespace:,timeout:" -n "${CALLED}" -- "${@}")" || usage
+
+CONTEXT_SET="false"
+CONTEXT=""
+NAMESPACE_SET="false"
+NAMESPACE=""
+TIMEOUT_SET="false"
+TIMEOUT="1h"
+DEBUG="false"
+
+eval set -- "${ARGS}"
+
+while true ; do
+	case "${1}" in
+		--help | -h | "-?" ) usage ;;
+
+		-- ) shift ; break ;;
+
+		--debug | -d ) DEBUG="true" ; shift ;;
+
+		--context )
+			[ "${CONTEXT_SET}" == "false" ] || usage "You may only provide ${1} once"
+			CONTEXT_SET="true"
+			CONTEXT="${2}"
+			[ -n "${CONTEXT}" ] || fail "The context may not be the empty string"
+			shift 2
+			;;
+
+		--namespace | -n )
+			[ "${NAMESPACE_SET}" == "false" ] || usage "You may only provide ${1} once"
+			NAMESPACE_SET="true"
+			NAMESPACE="${2}"
+			[ -n "${NAMESPACE}" ] || fail "The namespace may not be the empty string"
+			shift 2
+			;;
+
+		--timeout | -t )
+			[ "${TIMEOUT_SET}" == "false" ] || usage "You may only provide ${1} once"
+			TIMEOUT_SET="true"
+			TIMEOUT="${2}"
+			[ -n "${TIMEOUT}" ] || fail "The timeout may not be the empty string"
+			shift 2
+			;;
+	esac
+done
+
+[ ${#} -ge 1 ] || usage "Must provide the pod's name to wait for"
+[ ${#} -le 2 ] || usage "Too many positional parameters (expected at most 2!)"
 
 POD="${1}"
-shift
+[ -n "${POD}" ] || fail "The pod's name may not be the empty string"
 
 CONTAINER=""
-if [ ${#} -gt 0 ] ; then
-	CONTAINER="${1}"
-	shift
+if [ ${#} -gt 1 ] ; then
+	CONTAINER="${2}"
+	[ -n "${CONTAINER}" ] || fail "The container's name may not be the empty string"
 fi
 
-wait-pod "${POD}" || fail "Pod ${POD} did not come up on time"
+export K="$(type -P kubectl 2>&1)" || fail "Couldn't find kubectl in the path (rc=${?}): ${K}"
+export K_ARGS=()
+__k()
+{
+	"${K}" "${K_ARGS[@]}" "${@}"
+}
+
+__k_exec()
+{
+	exec "${K}" "${K_ARGS[@]}" "${@}"
+}
+
+CTX_ERR=""
+if [ -n "${CONTEXT}" ] ; then
+	OUT="$(__k config get-contexts "${CONTEXT}" 2>&1)" || fail "Couldn't validate the context [${CONTEXT}]"
+	K_ARGS+=( --context "${CONTEXT}" )
+	CTX_ERR=" for the context [${CONTEXT}]"
+fi
+
+NS_ERR=""
+if [ -n "${NAMESPACE}" ] ; then
+	OUT="$(__k get namespace "${NAMESPACE}" 2>&1)" || fail "Couldn't validate the namespace [${NAMESPACE}]${CTX_ERR}"
+	K_ARGS+=( --namespace "${NAMESPACE}" )
+	NS_ERR=" in the ${NAMESPACE} namespace"
+fi
+
+# We're going to pass these along to the wait-pod script, but without the trailing
+# container
+eval set -- "${ARGS}"
+
+ARR=( "${@}" )
+[ -n "${CONTAINER}" ] && unset 'ARR[-1]'
+
+wait-pod "${ARR[@]}" || exit ${?}
 
 if [ -n "${CONTAINER}" ] ; then
-	CONTAINER=(-c "${CONTAINER}")
+	CONTAINER=( -c "${CONTAINER}" )
 else
 	CONTAINER=()
 fi
 
-set -x
-exec kubectl logs -f "${CONTAINER[@]}" "${POD}"
+CMD=( __k_exec "${K_ARGS[@]}" logs -f "${CONTAINER[@]}" "${POD}" )
+${DEBUG} && set -x
+"${CMD[@]}"
diff --git a/tools/wait-pod b/tools/wait-pod
--- a/tools/wait-pod
+++ b/tools/wait-pod
@@ -5,7 +5,7 @@
 #
 set -eou pipefail
 
-CALLED="${BASH_SOURCE:-${0}}"
+CALLED="${BASH_ARGV0:-${BASH_SOURCE:-${0}}}"
 
 timestamp()
 {
@@ -17,45 +17,101 @@ say()
 	echo -e "$(timestamp): ${@}"
 }
 
+err()
+{
+	say "❌ ${@}"
+}
+
 fail()
 {
-	say "${@}" 1>&2
+	err "${@}"
 	exit ${EXIT_CODE:-1}
 }
 
 usage()
 {
-	echo -e "usage: ${BASH_SOURCE:-${CALLED}} [-d] [-t timeout] [-n namespace] [-h | -?] pod" 1>&2
+	[ ${#} -eq 0 ] || err "${@}\n"
+	echo -e "usage: ${CALLED} [ -h | -? | --help ] [ -d | --debug ] [ --context context ] [ -n namespace | --namespace namespace ] [ -t timeout | --timeout timeout ] pod" 1>&2
 	exit 1
 }
 
-# Default timeout is 1 hour
+ARGS="$(getopt -o "h?dn:t:" -l "help,debug,context:,namespace:,timeout:" -n "${CALLED}" -- "${@}")" || usage
+
+CONTEXT_SET="false"
+CONTEXT=""
+NAMESPACE_SET="false"
+NAMESPACE=""
+TIMEOUT_SET="false"
 TIMEOUT="1h"
-TIMEOUT_GIVEN="false"
-NAMESPACE="default"
-NAMESPACE_GIVEN="false"
 DEBUG="false"
-while getopts ":t:n:hd" OPT "${@}" ; do
-	case "${OPT}" in
-		t ) [ -z "${OPTARG}" ] && fail "May not specify an empty timeout value"
-			${TIMEOUT_GIVEN} && fail "May not give more than one timeout value"
-			TIMEOUT="${OPTARG}"
-			TIMEOUT_GIVEN="true"
+
+eval set -- "${ARGS}"
+
+while true ; do
+	case "${1}" in
+		--help | -h | "-?" ) usage ;;
+
+		-- ) shift ; break ;;
+
+		--debug | -d ) DEBUG="true" ; shift ;;
+
+		--context )
+			[ "${CONTEXT_SET}" == "false" ] || usage "You may only provide ${1} once"
+			CONTEXT_SET="true"
+			CONTEXT="${2}"
+			[ -n "${CONTEXT}" ] || fail "The context may not be the empty string"
+			shift 2
 			;;
-		n ) [ -z "${OPTARG}" ] && fail "May not specify an empty namespace"
-			${NAMESPACE_GIVEN} && fail "May not give more than one namespace value"
-			NAMESPACE="${OPTARG}"
-			NAMESPACE_GIVEN="true"
+
+		--namespace | -n )
+			[ "${NAMESPACE_SET}" == "false" ] || usage "You may only provide ${1} once"
+			NAMESPACE_SET="true"
+			NAMESPACE="${2}"
+			[ -n "${NAMESPACE}" ] || fail "The namespace may not be the empty string"
+			shift 2
 			;;
-		d ) DEBUG="true" ;;
-		: ) fail "Option -${OPTARG} requires an argument" ;;
-		h | \? ) usage ;;
+
+		--timeout | -t )
+			[ "${TIMEOUT_SET}" == "false" ] || usage "You may only provide ${1} once"
+			TIMEOUT_SET="true"
+			TIMEOUT="${2}"
+			[ -n "${TIMEOUT}" ] || fail "The timeout may not be the empty string"
+			shift 2
+			;;
 	esac
 done
-shift $(( ${OPTIND} - 1 ))
 
-[ ${#} -lt 1 ] && usage
+[ ${#} -eq 1 ] || usage "Must provide the pod's name to wait for"
 POD="${1}"
+[ -n "${POD}" ] || fail "The pod's name may not be the empty string"
 
+export K="$(type -P kubectl 2>&1)" || fail "Couldn't find kubectl in the path (rc=${?}): ${K}"
+export K_ARGS=()
+__k()
+{
+	"${K}" "${K_ARGS[@]}" "${@}"
+}
+
+__k_exec()
+{
+	exec "${K}" "${K_ARGS[@]}" "${@}"
+}
+
+CTX_ERR=""
+if [ -n "${CONTEXT}" ] ; then
+	OUT="$(__k config get-contexts "${CONTEXT}" 2>&1)" || fail "Couldn't validate the context [${CONTEXT}]"
+	K_ARGS+=( --context "${CONTEXT}" )
+	CTX_ERR=" for the context [${CONTEXT}]"
+fi
+
+NS_ERR=""
+if [ -n "${NAMESPACE}" ] ; then
+	OUT="$(__k get namespace "${NAMESPACE}" 2>&1)" || fail "Couldn't validate the namespace [${NAMESPACE}]${CTX_ERR}"
+	K_ARGS+=( --namespace "${NAMESPACE}" )
+	NS_ERR=" in the ${NAMESPACE} namespace"
+fi
+
+
+CMD=( __k_exec wait --timeout "${TIMEOUT}" --for=jsonpath="{.status.phase}=Running" "pod/${POD}" )
 ${DEBUG} && set -x
-exec kubectl wait --timeout="${TIMEOUT}" --for=jsonpath="{.status.phase}=Running" --namespace "${NAMESPACE}" "pod/${POD}"
+"${CMD[@]}"
